version: "3"
services:
  burnout_postgres:
    image: postgres:13.1
    restart: always
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=burnout
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: